active: test
SECRET_KEY: 581ac6ebda4b42189905ec4930407ce0
DEBUG: false
TESTING: false
SQLALCHEMY_ECHO: false
JSON_AS_ASCII: false
OPEN_SIGN_AUTH: true
PORT: 5000

# API 文档
API_DOC_MEMBER:
  - api
  - platform

# 数据库配置
SQLALCHEMY_DATABASE_URI: 'mysql://root:123456@127.0.0.1:3306/wallet'
SQLALCHEMY_COMMIT_ON_TEARDOWN: true
SQLALCHEMY_TRACK_MODIFICATIONS: true

SIGN_API:
  # 以这个开头匹配的都需要签名
  - /api/v1/

ENV:
  Environment: prod


LOG_CONF:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] {%(filename)s %(lineno)d} %(levelname)s - %(message)s'
  handlers:
    default:
      level: 'INFO'
      formatter: 'standard'
      class: 'logging.StreamHandler'
      stream: 'ext://sys.stdout'
    console:
      level: 'INFO'
      formatter: 'standard'
      class: 'logging.StreamHandler'
      stream: 'ext://sys.stdout'
    debug:
      level: 'DEBUG'
      formatter: 'standard'
      class: 'logging.StreamHandler'
      stream: 'ext://sys.stdout'
    file:
      level: 'INFO'
      formater: 'standard'
      class: 'logging.handlers.TimedRotatingFileHandler'
      filename: '/var/logs/wallet_manage.log'
      when: 'D'
      interval: 1
  loggers:
    default:
      handlers:
        - console
        - file
      level: INFO
      propagate: false
    debug:
      handlers:
        - console
        - debug
      level: DEBUG
      propagate: false
