DEBUG: false
TESTING: false
SQLALCHEMY_ECHO: false
OPEN_SIGN_AUTH: true

SQLALCHEMY_DATABASE_URI: 'mysql://root:123456@127.0.0.1:3306/wallet'
SQLALCHEMY_COMMIT_ON_TEARDOWN: true
SQLALCHEMY_TRACK_MODIFICATIONS: true

ENV:
  Environment: prod
